<?php

/**
 * Implements hook_user_login().
 */
function bibdk_frontend_user_login() {
  drupal_goto('');
}

/**
 * Implements hook_ctools_plugin_api().
 */
function bibdk_frontend_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implementation of hook_default_page_manager_pages().
 */
function bibdk_frontend_default_page_manager_pages() {
  $pages = array();
  $path = drupal_get_path('module', 'bibdk_frontend') . '/pages';
  $files = drupal_system_listing('/\.inc$/', $path, 'name', 0);
  foreach ($files as $file) {
    include_once $file->uri;
    $pages[$page->name] = $page;
  }
  return $pages;
}

/**
 * Implements hook_block_info().
 */
function bibdk_frontend_block_info() {
  $blocks['bibdk_tabs'] = array(
    'info' => t('Bibdk: tabs'),
    'description' => t('sidebar tab menu_local_tabs'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bibdk_frontend_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'bibdk_tabs':
      $block['content'] = menu_local_tabs();
      if (is_array($block['content']['#secondary'])) {
        foreach ($block['content']['#secondary'] as $n => $tab) {
          $block['content']['#secondary'][$n]['#link']['title'] = t($tab['#link']['title'], array(), array('context' => 'bibdk_frontend'));
        }
      }
      break;
  }

  //unset primary tab
  if (isset($block['content']['#primary'])) {
    unset($block['content']['#primary']);
  }
  return $block;
}


function bibdk_frontend_block_view_alter(&$data, $block) {
  if ($block->delta == 'menu-global-login-menu') {
    foreach ($data['content'] as $key => $value) {
      if (isset($value['#title'])) {
        $data['content'][$key]['#title'] = t($value['#title'], array(), array('context' => 'bibdk_frontend'));
      }
    }
  }
}


/**
 * Implements hook_menu().
 */
function bibdk_frontend_menu() {

  $items = array();

  $forms = array('all_element_types', 'all_inline_element_types');

  foreach ($forms as $form) {
    $items['bibdk_forms/' . $form] = array(
      'title' => t($form),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('bibdk_form_callback_' . $form),
      'access callback' => 'user_access',
      'access arguments' => array('access developer information'),
      'file' => 'bibdk_forms.inc',
      'type' => MENU_NORMAL_ITEM,
    );
  }

  return $items;
}












