<?php
/**
 * @file
 * Code for the article_view feature.
 */

include_once 'article_view.features.inc';

/**
 * Implements hook_preprocess_HOOK
 *
 * Add classes and fields that needs to be handled in special ways to
 * bibdk_articles_view
 * @param $vars
 */
function article_view_preprocess_views_view_fields(&$vars) {
  $view = $vars['view'];
  // only handle bibdk_articles_view
  if ($view->name != 'article_view') {
    return;
  }

  // get the node
  $node = node_load($vars['row']->nid);
  $wrapper = entity_metadata_wrapper('node', $node);

  $classes = article_view_handle_classes($wrapper);
  $vars['class'] = drupal_attributes($classes);

  // get link text
  $link_text = $wrapper->field_link_text->value();
  // get link url
  $link_url = $wrapper->field_link->value();


 if (!empty($link_text) && !empty($link_url)) {
    $attributes = array('attributes' => array('target' => '_blank'));
    $link = l($link_text, $link_url, $attributes);

    // iniitialize link object
    $vars['fields']['field_link']->content = $link;
    $vars['fields']['field_link']->label_html = '';
    $vars['fields']['field_link']->wrapper_prefix = '<div class="footer"><div class="field-read-more">';
    $vars['fields']['field_link']->wrapper_suffix = '<span class="icon icon-left icon-blue-right">&nbsp;</span></div></div>';
  }
}

function article_view_handle_classes($wrapper) {
  // get rows
  $rows = $wrapper->field_rows->value();
  // default value
  $rows = empty($rows) ? '2' : $rows;

  $region = $wrapper->field_page_region->value();
  if (!empty($region) && $region->name == 'top') {
    $classes = bibdk_article_get_classes(4, 'top', 'light-grey');
  }
  else {
    $classes = bibdk_article_get_classes($rows);
  }

  return $classes;
}

/**
 * callback method for bibdk_custom_header_block
 */
function article_view_get_panel_link() {
  $message = t('more_articles', array(), array('context' => 'bibdk_article'));
  $path = 'bibdk_articles';
  $link = array(
    '#theme' => 'link',
    '#text' => $message,
    '#path' => $path,
    '#options' => array(
      'attributes' => array(
        'class' => array('article-view-more-link'),
        'id' => 'article-view-more-id',
      ),
      'html' => FALSE,
    ),
  );
  return $link;
}
