<?php

module_load_include('inc', 'worktabs', 'worktabs.field');

/**
 * Implements hook_theme().
 */
function worktabs_theme() {
  return array(
    'worktabs' => array(
      'template' => 'theme/worktabs',
      'variables' => array('tabs' => array(), 'pid' => ''),
    ),
    'tab-item' => array(
      'template' => 'theme/tab-item',
      'variables' => array('title' => '', 'btn_txt_closed' => '', 'btn_txt_open' => '', 'content' => '', 'single' => FALSE),
    ),
  );
}

/**
 * @param $entity
 * @return string
 */
function worktabs_get_tabs($entity) {
  $content = array();
  $tabs = worktabs_get_content($content, $entity);
  $id = _worktabs_trim_string($entity->id);
  drupal_add_js(drupal_get_path('module', 'worktabs') . '/js/worktabs.js');
  return theme('worktabs', array('tabs' => $tabs, 'pid' => $id));
}

/**
 * @param $tabs
 * @param $entity
 * @return array
 */
function worktabs_get_content($tabs, $entity) {
  $content = module_invoke_all('worktabs_items', $tabs, $entity);
  $tabs = worktabs_merge_content($content);
  return worktabs_render_content($tabs);
}

/**
 * @param $tabs
 * @return mixed
 */
function worktabs_render_content($tabs) {
  foreach ($tabs as &$tab) {
    $content = '';
    foreach ($tab['content'] as $inner){
      $content .= theme('tab-item', array(
        'title' => isset($inner['title']) ? $inner['title'] : '',
        'btn_txt_closed' => isset($inner['btn_txt_closed']) ? $inner['btn_txt_closed'] : t('view_more', array(), array('context' => 'worktabs')),
        'btn_txt_open' => isset($inner['btn_txt_open']) ? $inner['btn_txt_open'] : t('view_less', array(), array('context' => 'worktabs')),
        'content' => isset($inner['rendered']) ? $inner['rendered'] : '',
        'single' => (count($tab['content']) >= 2) ? FALSE : TRUE,
      ));
    }
    $tab['content'] = $content;
  }
  return $tabs;
}

/**
 * @param $content
 * @internal param array $tabs
 * @return array
 */
function worktabs_merge_content($content) {
  $outertabs = worktabs_get_outer();
  foreach ($content as $tab => $inner) {
    $arr = array_merge($outertabs[$tab]['content'], $inner);
    uasort($arr, 'drupal_sort_weight');
    $outertabs[$tab]['content']  = $arr;
  }
  return $outertabs;
}

/**
 * @return array
 */
function worktabs_get_outer() {
  return array(
    'subjects' => array(
      'title' => t('Subjects'),
      'content' => array(),
      'class' => 'active',
      'active' => 'active',
    ),
    'more-about' => array(
      'title' => t('More Info'),
      'content' => array(),
      'class' => '',
      'active' => 'visuallyhidden',
    ),
    'reviews' => array(
      'title' => t('Reviews'),
      'content' => array(),
      'class' => 'inactive',
      'active' => 'visuallyhidden',
    ),
  );
}

/**
 * Strips a string (pid) for :, -, __
 *
 * @param string $string
 * @return string
 */
function _worktabs_trim_string($string) {
  return strtolower(strtr($string, array(':' => '', '-' => '', '__' => '')));
}
